# Common variables
nifi_name: nifi # Should be changed to your NiFi's FQDN
nifi_user: nifi # This user MUST have UID 1000
nifi_image: apache/nifi:2.0.0
nifi_home_dir: /home/nifi # NiFi's will store all of its data here by default
nifi_nar_extensions_dir: /data/nar_extensions # Custom NAR files

# Security
nifi_keystore: keystore.jks # Filename of your keystore on the Host machine
nifi_truststore: truststore.jks # Filename of your truststore on the Host machine
nifi_security_keystore_password: keystorepass
nifi_security_keystore_type: JKS
nifi_security_truststore_password: truststorepass
nifi_security_truststore_type: JKS

# Cluster mode
nifi_cluster_is_node: true # Enable or disable clustered mode
nifi_nodes:
# Cluster members. Without this, NiFi nodes will not be able to communicate with eachother
- dn: CN=nifi-devops-prd-01.domain.local, OU=NIFI
- dn: CN=nifi-devops-prd-02.domain.local, OU=NIFI
- dn: CN=nifi-devops-prd-03.domain.local, OU=NIFI

# Single user mode
nifi_single_user_mode: false
nifi_single_user_credentials_username: nifi
nifi_single_user_credentials_password: nifinifinifinifi

# Zookeeper
nifi_zookeeper_connect_string: my-zookeeper-server.com:2181 # your Zookeeper connection string.
